#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello world" when querie
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R 755 /var/www
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
