#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello world" when queried
#+     at the root with a curl GET request.
#+    Contains a custom HTTP header named X-Served-By.

apt-get -y update
apt-get install -y nginx

sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

service nginx start
