#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello world" when queried
#+     at the root with a curl GET request.
#+    Contains a custom HTTP header named X-Served-By.

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    }
service nginx restart
