#!/usr/bin/env bash
# configuring load balancer
# Add HAProxy PPA

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy

sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo tee /etc/haproxy/haproxy.cfg<<EOF
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
   balance      roundrobin
   server 31302-web-01        100.26.173.59:80 check
   server 31302-web-02        54.144.223.128:80 check

EOF
sudo service haproxy restart
